- .github/CODEOWNERS
- .github/auto_assign.yml
호림님이 안 계셔서 확인하고 머지해야 할 것 같습니다
논의 스레드: https://2025springswppimo.slack.com/archives/C08HW2053LM/p1744771028058419
> 👥 add codeowners & auto assign

- .github/workflows/daily-scrum.yml
> 👽 team-07 -> team-07-random

- scripts/daily-scrum/bun.lock
- scripts/daily-scrum/package.json
- scripts/daily-scrum/send.ts
> ✨ daily scrum 에서 오늘 할 일 보여주기

- scripts/daily-scrum/biome.json
- scripts/daily-scrum/bun.lock
- scripts/daily-scrum/package.json
- scripts/daily-scrum/src/entities/github.ts
- scripts/daily-scrum/src/entities/member.ts
- scripts/daily-scrum/src/entities/sprint.ts
- scripts/daily-scrum/src/entities/task.ts
- scripts/daily-scrum/src/infrastructures/dailyScrumBurndownChartPresenter.ts
- scripts/daily-scrum/src/infrastructures/dailyScrumGitHubOctokitRepository.ts
- scripts/daily-scrum/src/infrastructures/dailyScrumNotionHqClientRepository.ts
- scripts/daily-scrum/src/infrastructures/dailyScrumSlackWebApiPresenter.ts
- scripts/daily-scrum/src/main.ts
- scripts/daily-scrum/src/usecases/sendDailyScrumUsecase.ts
- scripts/daily-scrum/src/utils/ensure.ts
https://www.notion.so/Burn-Down-Chart-1e19614fd0a380bab239c9c4e87044aa?pvs=4
> ✨ slack 으로 burn down chart 보내기

- scripts/daily-scrum/src/infrastructures/dailyScrumBurndownChartPresenter/index.test.ts
- scripts/daily-scrum/src/infrastructures/dailyScrumBurndownChartPresenter/index.ts
> 🩹 하루 덜 나오는 버그 픽스

- SchoolRush/Assets/Scripts/SaveNickname.cs
- SchoolRush/Assets/Scripts/SceneManager.cs
포매팅 및 주석 등 관련해서 기본 규칙이 필요할 것 같아 수정 PR 올립니다
주석은 GPT가 작성한 걸로 보이기도 하고 오늘 수업에서 말씀주신 대로 DRY 위반인 것 같아서 제거했습니다!
> 🎨 fix format & remove unnecessary comment

- SchoolRush/Assets/Materials/Yellow.mat
- SchoolRush/Assets/Materials/Yellow.mat.meta
- SchoolRush/Assets/Scenes/GameScene.unity
- SchoolRush/ProjectSettings/TagManager.asset
> Minimap Init

- reports/sprint2/README.md
https://2025springswppimo.slack.com/archives/C08KVGJU4H4/p1747651245296919
> 📝 페어프로그래밍 로그 추가

- reports/sprint2/README.md
@SummerPea @cloNoey 페어프로그래밍 로그입니다.
> 📝 0519 페어프로그래밍 로그 추가(2)

- .github/CODEOWNERS
혼란을 방지하기 위해 @woohm402 만 코드오너로 남깁니다.
> 👥 update codeowners

- SchoolRush/Assets/Scripts/GameController/BGMController.cs
- SchoolRush/Assets/Scripts/GameController/BGMController.cs.meta
- SchoolRush/Assets/Scripts/Upgrades/UpgradeManager.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade402.cs
- SchoolRush/Assets/Sounds/BGM/Aegukga.mp3.meta
402 증강을 구현합니다. 애국가 음원은 저작권 없는 [공유마당](https://gongu.copyright.or.kr/gongu/wrt/wrt/view.do?wrtSn=13211046&menuNo=200020) 에서 `2018 애국가 (합창) 1~4절` 로 다운받았습니다.
애국가 변수 네이밍을 좀 고민했는데 `TheNationalAnthemOfKorea.mp3` 가 그렇게 와닿진 않을 것 같아서, 고유명사라고 생각하고 `Aegukga` 로 처리했습니다.
맥에서 음성 녹화가 잘 안 되어서 넣어두진 않았는데 잘 적용되었습니다.
https://www.notion.so/1ff9614fd0a3806d8524cb77c024a2ab?source=copy_link
> ✨ 402 증강 구현

- SchoolRush/Assets/Scripts/Kart/KartController.cs
- 드리프트 시 캐릭터도 차체의 움직임을 따라가도록 수정
- 동료 캐릭터 추가 (체크포인트마다 CharacterModels 하위 에셋으로 추가하면 됨)
- > 운전자 캐릭터는 핸들의 움직임에 따라 회전하도록
- > 동료 캐릭터들은 차체의 움직임에 따라 회전하도록
- > (드리프트하다가 핸들 방향이 바뀌는 경우에 위 설정(운전자/동료 움직임 분리)이 가장 적합)
https://github.com/user-attachments/assets/c09886ea-a118-4213-bcfc-d0f05eb974df
> fixed character moving error, add peer character

- SchoolRush/Assets/Scripts/Kart/KartController.cs
- SchoolRush/Assets/Scripts/Upgrades/UpgradeManager.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade201.cs
증강 201 "최고속도 50% 증가" 구현
https://www.notion.so/20d9614fd0a380a59fb6e13fba85e27c?source=copy_link
> implement Upgrade 201

- web/bun.lock
- web/package.json
- web/src/app/api/player-data/route.ts
#92 에서 쏘는 데이터를 받을 수 있도록 서버 핸들러를 구성합니다.
https://www.notion.so/ui-1e19614fd0a380829e49d55e264b14e9?source=copy_link
> ✨ 랭킹 대시보드 데이터 받는 서버

- SchoolRush/Assets/Scripts/Kart/KartController.cs
- SchoolRush/Assets/Scripts/Upgrades/UpgradeManager.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade101.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade102.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade202.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade203.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade301.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade302.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade303.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade401.cs
속도/가속도 관련 증강 구현 - 101, 201 구현 방식 그대로 적용하여 구현함
102, 202, 203, 301, 302, 303, 401
KartController.cs - player에 붙어있는 스크립트 인스펙터 값으로 적용되어서, 스크립트 값으로 설정되도록 public에서 private으로 수정
> 6/17 -> 속도/가속도 관련 리팩토링 진행 예정 + 204 증강(택시 에셋 적용과 함께 진행)
> 6/19 -> 체크포인트마다 동료 에셋 추가 관련 태스크도 진행할 예정
https://www.notion.so/20d9614fd0a380a59fb6e13fba85e27c?source=copy_link
> augments related to speed

- web/src/app/api/player-data/route.ts
- web/src/app/page.tsx
타입 이슈로 서버사이드에서 빌드가 안 되고 있었어서 픽스합니다.
> 🩹 fix web build

- SchoolRush/Assets/Scripts/Kart/KartController.cs
카트의 부스터가 프레임 드랍이 일어났을때, 충전에걸리는 시간도 오래걸리게 되는 문제를 해결하였습니다.
그리고 차량의 기본속력을 조금 증가시켰습니다
> kart booster

- SchoolRush/Assets/Scripts/Map/MMIndicator.cs
> 💄 bike, 버스 크기 조정

- SchoolRush/ProjectSettings/EditorBuildSettings.asset
> ⚰️ 삭제된 Scene 들 빌드 세팅에서 제거

- SchoolRush/Assets/Scripts/Kart/CollisionManager.cs
- SchoolRush/Assets/Scripts/Kart/KartController.cs
- SchoolRush/ProjectSettings/TagManager.asset
road위에있을때 최고속력이 올라가도록 설정하였습니다.
설정을 위해 모든 road 에 Road 태그를 추가했습니다.
resolved #125 
최고속도가 오른거라 스크린샷으로 볼 수 있는 변경사항은 없습니다.
> boostOnRoad

- SchoolRush/Assets/Scripts/Kart/KartController.cs
#142 PR에서 구현한 부분에서 도로에 있을떄 반대로 더 느려지는 버그가 발생하여 해결합니다
> fix road boost speed

- SchoolRush/Assets/Scripts/Kart/KartController.cs
택시로 증강 변경 시 위치 정문으로 가는 에러 수정
+ 살짝 떠있는 문제 최소화
(바퀴에 collider 설정하려고 했는데, 포기하고 그냥 단일 sphere로 진행 -> 심한 경사로에서 떠있는 문제는 어쩔 수 없음..)
> taxi position error fixed

- SchoolRush/Assets/Scripts/Map/MMIndicator.cs
- SchoolRush/Assets/Sound FX.zip.meta
fixed #148 
미니맵에 거리 표시 추가됨
https://www.notion.so/20d9614fd0a380948c5ddbdb2f573a0a
> Minimap bug fixed & distance added

- SchoolRush/Assets/Scripts/Kart/CheckpointManager.cs
- SchoolRush/Assets/Scripts/Kart/CollisionManager.cs
- SchoolRush/Assets/Scripts/Kart/KartController.cs
택시로 변신했을때 다음 체크포인트가 수정되지 않던 오류를 수정하였습니다.
passenger가 생성되지 않는 구역에 관련된 오류를 수정하였습니다.
> taxi checkpoint2, minor error

- SchoolRush/Assets/PequeTraffic/Scripts/CharacterNavigationController.cs
- SchoolRush/Assets/Prefabs/passenger.prefab.meta
- SchoolRush/Assets/Scripts/Kart/KartController.cs
택시로 변경되었을때 시점변경,
카메라가 따라가는 방식을 변경
fixed #149
> Taxiadjust

- SchoolRush/Assets/Materials/Light.mat
- SchoolRush/Assets/Materials/Light.mat.meta
- SchoolRush/Assets/Prefabs/CheckpointLight.prefab
- SchoolRush/Assets/Prefabs/CheckpointLight.prefab.meta
- SchoolRush/Assets/Scenes/GameSceneAndMap_Profiles.meta
- SchoolRush/Assets/Scenes/GameSceneAndMap_Profiles/Cylinder Profile.asset
- SchoolRush/Assets/Scenes/GameSceneAndMap_Profiles/Cylinder Profile.asset.meta
- SchoolRush/Assets/Scenes/SampleScene_Profiles/PostProcessing Profile.asset
- SchoolRush/ProjectSettings/TagManager.asset
checkpoint asset - light cylinder added
> checkpoint asset prefab added

- SchoolRush/Assets/Anim/LoadingCamera.controller
- SchoolRush/Assets/Anim/LoadingCamera.controller.meta
- SchoolRush/Assets/Anim/LoadingPanel.controller
- SchoolRush/Assets/Anim/LoadingPanel.controller.meta
- SchoolRush/Assets/Anim/anim_cam.anim
- SchoolRush/Assets/Anim/anim_cam.anim.meta
- SchoolRush/Assets/Anim/anim_panel.anim
- SchoolRush/Assets/Anim/anim_panel.anim.meta
- SchoolRush/Assets/Scripts/GameController/LoadingCamManager.cs
- SchoolRush/Assets/Scripts/GameController/LoadingCamManager.cs.meta
- SchoolRush/Assets/Scripts/GameController/LoadingManager.cs
- SchoolRush/Assets/Scripts/GameController/LoadingManager.cs.meta
- SchoolRush/Assets/Scripts/GameController/MapController.cs
- SchoolRush/Assets/Scripts/GameController/PauseMenu.cs
Fixed #201
게임 시작하기 전에 맵 구경 애니매이션 구현했음.
https://github.com/user-attachments/assets/963c66b3-8caf-4cd9-9600-36c5cceed776
> LoadingMap Animation Added

- SchoolRush/Assets/CarAI/Scripts/AggressiveCarSpawner.cs
- SchoolRush/Assets/Scripts/GameController/TrafficController.cs
- SchoolRush/Assets/Scripts/GameController/TrafficController.cs.meta
- SchoolRush/Assets/Scripts/Upgrades/UpgradeManager.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade104.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade404.cs
미구현이던 103, 404 증강을 구현합니다.
resolves #191
103 -> 도로에 다니는 차량만 절반 제거
404 -> 그냥 차량이면 싹다 제거
여서, 404를 구현하기 위해 AggressiveCarSpawner에 소환된 것도 다 제거하는 메서드도 추가했습니다.
> ✨ implement 103, 404

- SchoolRush/Assets/Scripts/Kart/KartController.cs
- SchoolRush/Assets/Scripts/Upgrades/UpgradeManager.cs
- SchoolRush/Assets/Scripts/Upgrades/Upgrades/Upgrade403.cs
resolves #216 
1초마다 50% 오르면 좀 플레이감이 안좋아서 0.25초마다 12.5% 오르게 해뒀습니다
https://github.com/user-attachments/assets/cabad151-5aa6-4370-8808-d83ebff1833d
> ✨ implement 403

- web/src/app/tutorial/_components/Items.tsx
PC에서 반응형이 깨지는 이슈가 있어서 main 영역 최대 너비가 600px이 되도록 조정합니다.
키보드로 이동 가능하면 좋을 것 같아서 추가합니다.
> 💄 반응형 고려 & 키보드로 이동 가능하게
